### ISSUE TITLE
One chart to rule them all (new base chart)

### ISSUE THREAD

**Issue by philipsens** [frankframework/charts#14]
The common library was a good idea, and it worked as it was intended. 
The idea was that all charts based on the library would have the same structure and would be forced to support some features. In practice, it took a lot of work when a change needed to be made, because a lot of the changes would need to be updated in multiple charts (which kind of defeats the point).

I want to create _one_ Helm chart which can be used as dependency or on its own. I'm hoping that this will make it easier to contribute and to understand the chart itself.

- [x] Create a new chart where all template of ff-common are copied over to
- [x] Remove the template definitions
- [x] Add `resources.yml` with #13 
- [x] Add `localUsers.yml`
- [x] Add new health endpoints
- [ ] yaml authenticator
- [ ] Add Frank!Console #12
- [ ] Deprecate `ff-common`
- [ ] Deprecate old `frankframework` versions
- [ ] Change subcharts
  - [ ] frank2example
  - [ ] ff-test
